### ISSUE TITLE
Koneksi.php belum diupload

### ISSUE THREAD

**Issue by AxleCode** [AxleCode/Togel-TokoGadgetOnline#1]
Koneksi.php belum diupload @kmgarisudana 
koneksi.php untuk menghubungkan database phpmyadmin lokal
![WhatsApp Image 2022-05-19 at 23 28 56 (1)](https://user-images.githubusercontent.com/93900125/169353223-e96462a1-b3cb-48e1-9b27-c7e6de1eec68.jpeg)

**Comment by kmgarisudana** [comment]
wes
